---
all:
  children:
    webservers:
      hosts:
        web-1:
          ansible_host: web-1.ru-central1.internal
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
        web-2:
          ansible_host: web-2.ru-central1.internal
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
    monitoring:
      hosts:
        zabbix:
          ansible_host: zabbix.ru-central1.internal 
          ansible_user: ubuntu        
          ansible_python_interpreter: /usr/bin/python3
